name: birdup
description: DRW Weather Station Client

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^4.2.0
  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  data_table_2: ^2.2.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  kiwi: ^4.0.1
  provider: ^6.0.2
  web_socket_channel: ^2.2.0
  protobuf: ^2.1.0
  linked_scroll_controller: ^0.2.0
  get_it: ^7.2.0
  url_launcher: ^6.1.5
  syncfusion_flutter_charts: ^20.2.45
  dio: ^4.0.6
  photo_view: ^0.14.0
  intl: ^0.17.0
  flutter_phoenix: ^1.1.0
  mailto: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^4.2.0
  build_runner: ^2.1.4
  flutter_lints: ^2.0.1
  kiwi_generator: ^4.0.1

flutter:
  uses-material-design: true
  assets: []
